### ISSUE TITLE
data race on chunk.Saved

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#155]
this property is concurrently ready by AggMetric and written to by cassandraStore without synchronisation. not sure how to most elegantly fix, our locking in AggMetric is on AggMetric level, we don't have locks on individual chunks. We could track a pointer to the AggMetric in the ChunkWriteRequest for cassandraStore to use

**Comment by woodsaj** [comment]
I think we need to add the mutex on the individual chunks.  A chunk can exist outside of a aggMetric, eg if the chunk is added to the writeQueue and then bumped from the AggMetrics circular buffer.

**Comment by Dieterbe** [comment]
fixed by #485
