### ISSUE TITLE
what is eventdef/test_conf/elasticsearch.yml for ?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#193]
i don't see where it is being used. can we delete it?

**Comment by Dieterbe** [comment]
ping @ctdk

**Comment by Dieterbe** [comment]
ping @ctdk

**Comment by ctdk** [comment]
@Dieterbe That elasticsearch.yml file was there for running elasticsearch channel tests. It looks like @woodsaj refactored running elasticsearch out of the tests though - can he confirm? It looks like it's not used anymore.

**Comment by Dieterbe** [comment]
bd2e8367580af5feccb5f32b7f12107dcdb0d486
