### ISSUE TITLE
metricTank: add ability to delete metricDefs from the index

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#205]
see: https://github.com/raintank/ops/issues/276

Need an API endpoint through which we can issue a delete request.
- delete by metricId
- delete by orgId and series name.  eg orgId=1&series=litmus.*

**Comment by Dieterbe** [comment]
@woodsaj the latter is implemented but not the former. do you think we really need it? Why? I think we're good.

**Comment by woodsaj** [comment]
yeah, I think we are good.  I can't think of any scenario where the current delete method would be insufficient.
