### ISSUE TITLE
new repository organisation discussion for raintank-metric / data platform

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#206]
problems with our current repo setup:

* graphite-raintank in a separate repo is annoying because changes are often tied to metric-tank changes, so we need to update stuff independently that actually is quite dependent https://github.com/raintank/graphite-raintank/issues/24
* any time anything changes in raintank-metric, we trigger new builds of all binaries and build new versions of the packages.  this is annoying because there's a lot of "changes" for each tool where only 1 tool was actually affected. @woodsaj suggested to solve this by having 1 repo for all libraries, and a separate repo for each tool. (note that beside metric-tank, we currently have 6 tools, and i can see this grow easily until 10+) and managing versioning with gopkg.in
* the general case of my first point, when there's dependencies from one thing to other, I like to keep em in the same repository. (we have some schema and library packages that a lot of the tools use).  this helps with refactoring and testing all at once instead of juggling multiple repos and spending time dealing with metadata to keep them in sync. also it's easy to do a library change and forget to update all the tools that depend on it, or by the time you get to the last one you realize the library change made it really hard to be implemented in that tool and you realize you should have done the library change differently.
also it's annoying to do feature branches and PR's when multiple repo's are affected. then you need to do them for each, and the extra work of switching branches in different places.  also often issues relate to a thing as a whole (e.g. a library as well as a tool or multiple tools) and should be looked at holistically and only having the issue in 1 place (or worse, moving the ticket around repo's as discussions and thoughts around where we need to fix something evolve) is cumbersome and a distraction.
several organisations choose to go with monorepos (repositories hosting multiple libraries and tools) and this comes with some advantages as described at https://blog.gopheracademy.com/advent-2015/go-in-a-monorepo/ and https://pbs.twimg.com/media/Cc5cIpiWEAIgx-M.jpg and http://danluu.com/monorepo/

I believe we can solve both AJ's points and mine by doing something like a monorepository, but not as extreme. we wouldn't put everything we do in one single huge repo, but at least everything that has to do with our data processing and storage platform is tied together so can be kept in one place.
(practically we can just keep using this repo, move graphite-raintank into it, maybe reorganize it a bit, and over time incorporate more things wrt kafka, metrics ingestion, timeseries processing etc)

as for how to solve the versioning & packaging problem, we can use something like this:

```bash
#!/bin/bash

basepath=github.com/raintank/raintank-metric/

function packagesUsed() {
	go list -f '{{join .Deps "\n"}}' ./... | sort -u
}

function packagesChanged() {
	git diff-tree --name-only -r HEAD 'HEAD^' | xargs dirname | sort -u | sed "s#^#$basepath#"
}

comm -12 <(packagesUsed) <(packagesChanged) | grep ''
```

when run in the directory of an executable (e.g. in $GOPATH/src/github.com/raintank/raintank-metric/metric_tank), it exit(0)'s if something relevant has changed and exit(1)'s if nothing relevant has changed.

so we can just run it in all directories that represent a program and can decide to rebuild each individually.
someone on the internet said (TM) this is easy to do with circleci by using test.override https://discuss.circleci.com/t/building-monorepo-projects-with-circleci/1923/8 though i'm not very familiar with circleci.

@woodsaj @ctdk @torkelo @DanCech thoughts?

**Comment by woodsaj** [comment]
I strongly believe that libraries/binaries should only share the same repository when changes to one cant be deployed without changes to the other.

The idea of putting everything in the same repo just seems like an attempt to have to avoid versioning the software properly.

I dont think that graphite-raintank and metric-tank should be in the same repo.  The majority of the time these two pieces of software will be modified independently of each other.   Instead we just need to version everything properly and specify dependencies.  When new features or breaking changes are added to metric-tank, then its version should be incremented.  A corresponding new version of graphite-raintank can then be made.

Using separate repos for each component falls along the same line as writing modular code. It allows each module to be independently maintained, tested and supported.

**Comment by ctdk** [comment]
I lean more towards having separate repos, although libraries that are clearly related should be together.

**Comment by DanCech** [comment]
I'm with awoods on this one.

**Comment by Dieterbe** [comment]
I'm surprised none of you commented on any of the issues I mentioned in my 3rd point.  I regularly encounter all these and it's annoying. Do you recognize some of the mentioned issues but think they're a small price to pay? Did i explain things poorly? Did you not recognize these issues?
Do you have suggestions on how to development of features that often span multiple repositories?

**Comment by ctdk** [comment]
@Dieterbe Organizationally, I think the separate repo way is cleaner. I've found, at least in practice, that the headaches come up more often like in the raintank-metric repo where only tangentially related items are in the same repo (and the layout is a bit of a mess, because there's commands and libraries in there, but ironically no buildable go code in the root), where you aren't really quite sure if everything needs updated or not.

Anyway, the tons-of-repos way has its own problems but I think it ends up being better than one monolithic repo in the end. I would even say that we should have more than one library repo (although not one repo for every library item), for where chunks of the library don't have anything to do with each other.

**Comment by DanCech** [comment]
Personally I feel that a lot of the things touted as benefits of a monorepo are the opposite, and cut against the grain of both a microservices architecture and our open source model.

The ability to refactor something across the entire organization is interesting, but for that to work in the real world also means that you would need to have a unified deployment system and keep all the deployed code in sync unless the changes are backward compatible, and if they are compatible then there's no need to refactor everywhere in a single commit.

Saying that it makes dependency management easier also doesn't really make sense to me, since it means that to update the version of a library that your code uses you have to go find all code across the monorepo that uses that library and update it too.  If you instead get around that by maintaining multiple versions of the library in the monorepo, then you haven't actually gained anything there either.  Of course you can follow the DO model and "rarely (need to) bump third party dependencies", but good luck with that plan.

In the end I don't really understand what the monorepo is trying to solve, and it sounds like we'd actually be better off splitting into a scenario where shared libs are in a raintank-common repo or in their own repos, then each tool (or set of related tools) also has a repo.  If you pin dependencies to particular versions (or commits) then you can easily make changes by first updating the library then updating things that depend on it to use the new version, and if something keeps using the older version for a while then that's fine.

**Comment by woodsaj** [comment]
@Dieterbe you made this comment as a reason for having a monorepo
> also it's easy to do a library change and forget to update all the tools that depend on it

For raintank-metric, currently the assumption is already being made that the only code that uses the libraries you are changing are in the raintank-metric repo.  However this is not true and i often find other software that we build (worldping-api, task-server, etc...) that use the libraries suddenly break.

The concept of a monrepo just seems so backwards to me.  What is the delineation between what goes in the monorepo and what stays out. Why are internal software projects that are dependencies treated differently to external projects which are used as dependencies.    

I could understand a monorepo if all the interdependent projects are maintained by a single developer/team but this already not true now and will become less true as we hire more staff.  What if we want to give an external contractor write access to a project?  If we use a monorepo, they get write access to every project, which is probably not a good idea.

**Comment by DanCech** [comment]
Yup

**Comment by Dieterbe** [comment]
>  if they are compatible then there's no need to refactor everywhere in a single commit.

it's not so much about needing it, rather than that it's more efficient, easy and less impactful (from a code perspective) to do this way. Especially for feature development where you can do things in a single feature branch as opposed to, for example, having 3 repos that each need a feature branch and updated references to each other's feature branch. I've ran into this situation a few times (well, with only 2 repo's i think) and it's my main pain point. 

But this becomes less useful/true as soon as there's external code that we maintain that depends on code in the monorepo, which AJ correctly pointed out, is not true.
This would not be a problem if we were a closed source company and had *everything* in one giant repo, but since we definitely want to keep certain projects separate and have some more complex dependency graphs (for example raintank-docker is affected by both grafana changes as well as metric-tank changes) it wouldn't buy us much.

So we might as well get used to it and come up with a script to, for example "find all code under $GOPATH/src/github.com/raintank that imports $GOPATH/src/github.com/raintank/lib/somelib" because if i change somelib i should probably check out how somelib is being used by our projects and/or update most of our projects (at least the ones i maintain) (writing this script should be pretty trivial).

this does bring up the question: if we split into a whole bunch of repos, how do we pin the dependencies and use vendoring? (typically two approaches: reference a commithash/version number, or pull in the actual code). i would like to pull in the actual code (especially for 3rd party code that might disappear, and to be resilient against github.com going down - which has happened a few times) which means we would also do the same for our own code, basically duplicating the same code (for example some of our libs) to a whole lot of our repo's vendor folders.  I can live with this, can you guys?

so as far as repo re-org, some thoughts. let me know what you think:
* rename raintank-metric to metric-tank (most of the issues in this repo are re: MT, migrating MT to a different repo would mean an ugly migration of issues)
* we can then move the tools out of this repo (do we really want a separate repo for every single tool? i think i'm ok with this, just want to make sure this is what you guys want) 
* `dur` is a neat lib that could go into its own toplevel under raintank
* the libs that are used by both MT and some of the tools (metricdef, msg, schema, app, etc) could maybe go under github.com/raintank/lib) though schema could maybe also get its own top level repo since we want to encourage others to use this, so it could use the visibility.
* eventdef is only used by nsq_probe_events_to_elasticsearch so maybe that could go into that repo (and while we're at it, maybe rename to event-indexer or something)

**Comment by woodsaj** [comment]
- good call on just renaming raintank-metric to prevent migrating issues.
- i dont have a strong opinion on the tools, i dont really use them.  If they are always used together then it would make sense to keep them together.
- yes, please rename nsq_probe_event_..... to event-indexer or event-tank

**Comment by Dieterbe** [comment]
ok I finally took care of this. it was kindof a must that was blocking some other stuff.
you'll notice a bunch of new repos created in our github, for various tools and libs, and the old raintank-metric is now simply metrictank. also it's no longer metric-tank with a hyphen. it should be metrictank every where, including package names etc.

there will be some broken imports and builds throughout our various projects, we'll have to fix them as we encounter them. also i'm not super comfortable with circleci so i hope others can chip in. cc @ctdk @woodsaj @DanCech
