### ISSUE TITLE
replace ES as metricIndex store

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#222]
Some options include

- Use Postgres with its support for ltree and jsonb datatypes it can handle most querying use cases.

- use metric-tank as the interface to query the index.  Metric tank can store the index in memory and then just needs to persist the index items to permanent storage.  The permanent storage could be:
     - each metric-tank node has its own local boltdb database file.  We would need a way for new nodes to populate their index from a peer at startup.
     - use cassandra

**Comment by Dieterbe** [comment]
can't we use ES as a source of truth, with ES only written to when there's updates? that's where the current defcache/index was going for.  If we remove the "update every 6h even if there's no updates" piece this will probably work fine. (though i would trust postgres more than ES from a data safety perspective). ES may not be the most efficient, but it would be least amount of work.

the idealist in me would love to do pure-go with the built-in index and built-in persistence (boltdb could work well). could be in-MT-process or a service next to MT, i have no strong opinion on that yet.  but there's some issues:
* load balancing / sharding / partitioning will be tricky and require lots of dev effort. OTOH we will probably need to solve this problem (or bypass it) first for the in-memory data, and however we handle that, we will probably be able to use the same technology or workaround for the metric-index.
* tracking metadata changes over time needs to be implemented.

so using a clustered database as source of truth seems a lot safer. i wonder how postgres performs for some typical access patterns (with wildcards etc) and under high concurrency load.

**Comment by ctdk** [comment]
I think using Postgres would be the most straightforward, honestly. Anthony did those quick tests that looked really good, and I've used ltree in the past to good effect as well. Also, we could move our grafana and worldping databases over to postgres as well, so we wouldn't have to have both postgres and mariadb floating around causing trouble.

As far as performance postgres should be fine. Goiardi uses ltree for its search (optionally), and I've tested it with millions of rows with patterns a lot more complicated than wildcards and had no problems. At one point in time MySQL was definitely faster in the general usage case, but I think that's not so much an issue anymore. Certainly part of postgres' thing is being stable and reliable under load, so I'm not worried there.

**Comment by woodsaj** [comment]
Postgres still has no good clustering support though.  Though the postgres team have started to focus on clustering as a core feature, nothing exists yet.

**Comment by woodsaj** [comment]
ES is a terrible choice for us.  The only thing ES has going for it is its querying capabilities.  But if we are not using those, there is no point to use it.

- loadbalancing is easy to resolve, but also not a problem right now.  The index is infrequently updated and so update events can be broadcast to all nodes over the message Queue (nsq/kafka).  This enables the total metric volume to be split between indexing nodes, while still allowing each node maintain a complete index.
- this is more important, but i am really happy to just maintain first_seen, last_seen timestamps, with the last_seen being periodically updated.     If a metric is not seen for a long time then seen again, I am ok with treating it as though it was seen the entire time.

**Comment by ctdk** [comment]
I believe I had expressed some concern about the clustering part of postgres when we talked about this over the weekend. We would, of course, need to figure out which (if any) of the solutions currently available would work for us. I thought you were looking at pg-pool-II in a positive light, which was why I threw in behind postgres.

**Comment by woodsaj** [comment]
Another issue i have noticed with postrges
- you cant search for **metric.n*me.something**.  (postgress only allows * at the end of a label)

So this would mean that you would just have to search for "*" then perform normal regex match on the results, which isnt that big of a deal but worth mentioning.

What i do like about Postgres is that it allows us to efficiently query using the ltree on the metric path, which we need now, and also allow these queries to be combined with filtering on tags stored in a jsonb column, which we want later.

If we take the route of our own search index, we already have the path search capabilities done, but would need to implement the additional tag based filtering later on.  But on the plus side, the metric-tank service removes an additional external dependency, leaving only Cassandra (though a message queue like kafka would still be needed for large deployments).

**Comment by ctdk** [comment]
After looking it over again, with the assumption that we want synchronous multi-master, that either pgpool-II or BRD would be what we'd want if we did decide to go with Postgres:

* http://www.pgpool.net/mediawiki/index.php/Main_Page
* http://bdr-project.org/docs/stable/index.html

However, using either of these might be more complicated than we want to engage in (but I have a feeling it would still be less complicated than trying to write our own).

For a search like **metric.n*me.something**, you *might* not need to do a regex on the results - it may suffice to add a different index on that field. I'll look at what I did for that case and report back -- the goiardi postgres-backed search works in a very similar way to what we'd want here, so while presumably a lot of the code wouldn't be relevant there's lessons there that would help figure out if it would work well for us.

**Comment by ctdk** [comment]
Never mind with avoiding the regexp on results; I was thinking of indexes on a different column that the ltree path.

**Comment by woodsaj** [comment]
There have been some good discussions on options for an new index, both in the levelDB PR and also on slack. 

It is fairly clear that a cassandra backed index is preferred as it removes an external dependency from metrictank.  

@wyndhblb has provided some great details on a cassandra backed index at: https://raintank.slack.com/archives/metrictank/p1470145630000026

But i have some concerns on performance of this approach for metric/find searches as the queries to the index return all series that match the pattern, which then need to be processed to find the unique branches.  For example.  If you have a 1million series, then sending the query "metrics/find?query=*" will result in all 1 million series being fetched from Cassandra only to then need to be processed down to the unique branches in the series path at position 0.  If all the series share a common root node, eg "collectd" then that is a lot of processing to get a single branch node.

Here is a thought that i have.

```
CREATE TABLE metrictank.idx (
    org_id int,
    length int,
    path text,
    leaf boolean,
    PRIMARY KEY (org_id, length, path)
) 
```

Here we create an entry for every unique branch/leaf known. 
so the series 
```
A1.B1.C1.D1
A1.B1.C1.D2
A1.B1.C2.D1
A1.B2.C1.D1
```
result in the these inserts into the table
```
INSERT INTO idx (org_id, length, path, leaf) values(1, 1, 'A1', false);
INSERT INTO idx (org_id, length, path, leaf) values(1, 2, 'A1.B1', false);
INSERT INTO idx (org_id, length, path, leaf) values(1, 2, 'A1.B2', false);
INSERT INTO idx (org_id, length, path, leaf) values(1, 3, 'A1.B1.C1', false);
INSERT INTO idx (org_id, length, path, leaf) values(1, 3, 'A1.B2.C1', false);
INSERT INTO idx (org_id, length, path, leaf) values(1, 4, 'A1.B1.C1.D1', true);
INSERT INTO idx (org_id, length, path, leaf) values(1, 4, 'A1.B1.C1.D2', true);
INSERT INTO idx (org_id, length, path, leaf) values(1, 4, 'A1.B1.C2.D1', true);
INSERT INTO idx (org_id, length, path, leaf) values(1, 4, 'A1.B2.C1.D1', true);
```

We then perform "prefix" searches in Cassandra which are possible due to using "path" as a clustering key, which are sorted.  

### metrics/find?query=*

```
SELECT * from idx where org_id=1 AND length=1
```
 returns just "A1"

### metrics/find?query=A1.*
```
SELECT * from idx where org_id=1 AND length=2 AND path > "A1.\u0000" AND path <  "A1.\uFFFF"
```
 Here we use a range scan of path over every item that starts with "A1." and has a length of 2.
returns "A1.B1", "A1.B2"

### metrics/find?query=A1.{B1,B2}.*
```
SELECT * from idx where org_id=1 AND length=3 AND path > "A1.B1.\u0000" AND path <  "A1.B1.\uFFFF"
SELECT * from idx where org_id=1 AND length=3 AND path > "A1.B2.\u0000" AND path <  "A1.B2.\uFFFF"
```
As each query returns just the data we want, we can just perform two queries and union the results.

### metrics/find?query=A1.B\*.*
```
SELECT * from idx where org_id=1 AND length=3 AND path > "A1.B\u0000" AND path <  "A1.B\uFFFF"
```
Here, we can again use a prefix scan to get the exact results we want.


### metrics/find?query=A1.\*1.*
```
SELECT * from idx where org_id=1 AND length=3 AND path > "A1.\u0000" AND path <  "A1.\uFFFF"
```
Because the wildcard is at the beginning of the path node, this is the same query we would use for matching "A1.\*.*", and we will then need to filter the results using Regex on the client side.

**Comment by woodsaj** [comment]
A cassandraBacked index was merged in https://github.com/raintank/metrictank/pull/301

This index relies of the MemoryIdx for searching and just stores the metricDefs in cassandra as binary blobs.   At startup, the memory index is rebuilt from the data in cassandra.  On my desktop, the rebuild rate is 110,000 metricDefs per second, and my desktop is slow.
