### ISSUE TITLE
more proper config mechanism

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#231]
our config situation grew out of the legacy mechanism which was config flag based, but we added config file support in #45 , which let us set variables through config file, flags, or both.

some issues with this approach:
1) if we want to create new sections ("segments"), such as for different input plugins, they cannot be represented by commandline flags. AFAICT . I think they also can't be represented by environment variables.
2) no support for nested sections like:
```
listen_addr
[inputs]
[input-carbon]
carbon ..
```

3) one the selling points of the library is it supports rewrite the config file when changes are made at runtime (via config flags) see https://github.com/rakyll/globalconf#modifying-stored-flags.
This is not something we want, since config files should be controlled through CM (in our chef).
I believe we don't invoke this functionality as long as we stay away from `.Set()` and `.Delete()` calls, but it seems safer if this was absolutely impossible to begin with)

we may want to look at more advanced systems such as https://github.com/spf13/viper which also provides some other cool features we may want down the road.

however for now I don't think 3 is a big problem, 2 neither, just simple un-nested sections will work fine.

1 might be a problem though, i can live with the restriction for flags but @ctdk will it be a problem that certain things (e.g. input plugins kafka vs carbon vs http) can't be controlled through env vars? do you still need that?

for now, the carbon and kafka-mdm input use a segment in config file (so can't be changed through cmdline flags), whereas kafka-mdam input can be, but they are in the global section in the config file which is not very pretty but also not a huge deal.

**Comment by woodsaj** [comment]
To support running in  kubernetes we need support for env vars or command line flags.

**Comment by Dieterbe** [comment]
I was at least half wrong about point 1.  It is possible to override sections with env vars. i haven't figured out how to do it with params but that's ok. env vars should do it for now. see https://github.com/rakyll/globalconf/issues/15

we did need 2 fixes: c4023dea6414591f4f144fc043cd328a7d93e37a and 55a85b9af2bc5dde9f621ad710bc01b94223912a

that makes something like `MT_KAFKA_MDM_IN_PARTITIONS=6 ./build/metrictank` work.

since this gets us all we need - for now - I'm going to close this.
