### ISSUE TITLE
should ignore metrics ingestion that have the same keys as the output of rollups

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#237]
currently they can conflict

**Comment by woodsaj** [comment]
How is this possible?  The keys for raw metrics are the md5sum of the the metricDef fields.  The keys for rollup outputs are the raw metric Ids + the aggregation info.

eg. a raw metric with id 1.e2c569be17396eca2a2e3c11578123ed, would have rollups of the form 1.e2c569be17396eca2a2e3c11578123ed_min_600  to indicate a 10min rollup consolidated with min()

**Comment by Dieterbe** [comment]
you're right. i was only imagining this problem.
