### ISSUE TITLE
interesting ramp-up behavior

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#254]
not necessarily a bug or issue,
but it's interesting that when MT starts consumption, it slowly seems to ramp up consumption instead of consuming fully from the beginning.
see https://snapshot.raintank.io/dashboard/snapshot/bZOa5wxKSZzcrLK0ZJXi5iatiK1fSdBS

**Comment by woodsaj** [comment]
99.9% sure this is due to indexing to es slowing things down

**Comment by Dieterbe** [comment]
probably. anyway kind of silly we never monitored ES ingestion speed, but i will add it to the dashboard. that will clarify that in the future.
