### ISSUE TITLE
debs and rpms different naming

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#262]
see https://packagecloud.io/app/raintank/raintank/search?filter=all&q=metrictank-0.5.1&dist=
i can only see debs for 0.5.0, not 0.5.1

**Comment by woodsaj** [comment]
something wrong with packageclouds search.  the debs are there.

https://packagecloud.io/raintank/raintank?filter=debs

https://packagecloud.io/raintank/raintank/packages/ubuntu/xenial/metrictank_0.5.1-12-g931cf1d_amd64.deb

**Comment by woodsaj** [comment]
ahh, deb packages are named with an underscore between the package name and the version.

**Comment by Dieterbe** [comment]
is it desired to have this difference? something inherent to the deb vs rpm packaging system? or should we make this uniform?

**Comment by woodsaj** [comment]
This is not being changed by us.

The last package built in circleci was https://770-30401116-gh.circle-artifacts.com/0//home/ubuntu/metrictank/build/systemd/metrictank-0.5.1-12-g931cf1d_x86_64.deb

after being uploaded to packagecloud it has the name https://packagecloud.io/raintank/raintank/packages/ubuntu/xenial/metrictank_0.5.1-12-g931cf1d_amd64.deb

looks like packagecloud builds the deb file name from the package metadata.
name = metrictank
version = 0.5.1-12-g931cf1d
arch = x86_64 (aka amd64)

**Comment by ctdk** [comment]
It's inherent to the deb and rpm packaging conventions. The truly correct thing to do would be to adjust the names of the packages we're building to match, but since packagecloud does the right thing I'm not especially concerned.
