### ISSUE TITLE
docker guide: statsdaemon can sometimes not flush metrics to metrictank

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#277]
while the docker guide seems to work generally, and stats from statsdaemon come through, and i can send metrics into metrictank:2003 really well, statsdaemon for some reason is not always able to flush and throws errors like `ERROR: failed to write stats - write tcp 172.18.0.4:42222->172.18.0.5:2003: i/o timeout`. this might be a statsdaemon issue. not sure yet.

**Comment by DanCech** [comment]
confirming that I see the same behavior here

**Comment by Dieterbe** [comment]
fixed in statsdaemon
