### ISSUE TITLE
docs: recommend any particular cassandra settings?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#286]
@ctdk or @woodsaj is there any cassandra config settings we should recommend? now it just says "use the defaults"

**Comment by woodsaj** [comment]
use the defaults.  The only config item we tweak is the snitch (which is dependent on where cassandra is deployed and for a single instance is irrelevent), concurrent_reads and concurrent_writes which are dependent on disk,CPU resources, but defaults will be appropriate for most users.

For those wanting to tune they should refer to http://docs.datastax.com/en/cassandra/3.x/cassandra/configuration/configCassandra_yaml.html which provides better advise then we ever could.

**Comment by Dieterbe** [comment]
kthx!
