### ISSUE TITLE
idea: kafka as persistent index of metadata

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#292]
this depends on another idea which has come up before: splitting the data and metadata stream.
we want to do this so that the data stream is more compact, less redundant, and uses less i/o and cpu resources for encoding and decoding.
an optimisation for the metadata stream is that any agent or client (e.g. tsdb-gw) wanting to put data in the queue, does not have to put the same metadata into the metadata stream if it knows for sure it already did so for a given metricdef id.  While there will still be duplicate metadata messages (eg different clients putting in data for the same metric into the queue, or tsdb-gw restarted and lost track of which defs it queued up or not), there will considerable de-duplication.

anyway,
I got inspired by reading:
https://cwiki.apache.org/confluence/display/KAFKA/Log+Compaction
http://spootnik.org/entries/2015/03/10_simple-materialized-views-in-kafka-and-clojure.html (cheers @pyr)

it seems to me that if we set the `log.cleanup.policy = compact` option on the metadata topic, then we can **use kafka itself as the highly available, persistent source of truth for the metadata index**

a new MT instance can just read the kafka topic from offset=0 to backfill its in memory index.
a running MT instance just "follows" the kafka topic.
MT instances only nead to read in metadata messages and store them in-memory, they don't need to persist the data anymore.

@woodsaj thoughts?

**Comment by woodsaj** [comment]
i dont think it is a very good idea.

- in order for the log not to grow indefinitely with duplicates the clients would need to keep a persistent store of what metrics have been added to the index.  
- this approach has no support for deleting metrics from the index.
- makes kafka a dependency even when you are not using kafka for ingestion.

- provides no benefits over storing the metricDefs in Cassandra and re-indexing at startup.

**Comment by woodsaj** [comment]
However i do like the idea of splitting the ingestion stream into a metadata topic and a data topic.  So that for the majority of metrics, metrictank only needs to unmarshal <id> <value> <ts> and not the full metricData payload.

**Comment by Dieterbe** [comment]
> in order for the log not to grow indefinitely with duplicates

no. this is exactly what the log compaction solves

> this approach has no support for deleting metrics from the index.

it does. a message with a null payload is used for deletions. (def still needs to be deleted from MT itself but that's the same for any persistency solution). 

> makes kafka a dependency even when you are not using kafka for ingestion.
> provides no benefits over storing the metricDefs in Cassandra and re-indexing at startup.

it would of course be an optional index plugin, just like ES will be optional. and most appropriate when already using kafka for ingest/clustering.
But you do have a good point that it doesn't help with people who don't use kafka. and using cassandra as a backend solves it for everyone. 
Part of my reasoning is that long term we may not stick to cassandra, as the more we use big chunks we, the less we use cassandra as a database, and more as a blob store, for which it is a bit overkill.  But anyway that's not a problem at this point, and for the foreseeable future we're sticking to it, so I agree that if we can implement it in cassandra in an efficient way, let's do that instead of this.
