### ISSUE TITLE
configurable keyspace

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#294]
we have an environment where we want to have different customers (with their own metrictanks), but the same backing cassandra cluster.   we want to use different keyspaces per cassandra,
so keyspace should be configurable in metrictank.

see https://github.com/raintank/ops/issues/352

**Comment by woodsaj** [comment]
completed in https://github.com/raintank/metrictank/pull/303/commits/de7e7c9fc35649b1a3d15fead4f9c006a632e146
