### ISSUE TITLE
consumer/broker/0 abandoned subscription to metricpersist/0 because consuming was taking too long

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#298]
it's relatively easy to trigger this, 
e.g. with `./haggar -spawn-interval 1s -agents 50 -jitter 1ms` (50kMetrics/s) on a DO 4-core server.
I thought maybe it was related to ES backpressure which slows down the msg processing.
but also `./haggar -spawn-interval 5s -agents 50 -jitter 1ms` does it.
note this is with `chunkspan = 3min`.  maybe not the best idea.
it also means data will stop loading for a while.
https://snapshot.raintank.io/dashboard/snapshot/Mlfe6I92ZthGzbzy9NS5653pTxsEia4a
```
Aug 25 12:39:56 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:39:56 consumer/broker/0 abandoned subscription to metricpersist/0 because consuming was taking too long
Aug 25 12:39:56 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:39:56 consumer/broker/0 added subscription to metricpersist/0
Aug 25 12:40:03 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:03 consumer/broker/0 abandoned subscription to metricpersist/0 because consuming was taking too long
Aug 25 12:40:03 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:03 consumer/broker/0 added subscription to metricpersist/0
Aug 25 12:40:04 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:04 consumer/broker/0 abandoned subscription to metricpersist/0 because consuming was taking too long
Aug 25 12:40:04 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:04 consumer/broker/0 added subscription to metricpersist/0
Aug 25 12:40:06 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:06 consumer/broker/0 abandoned subscription to metricpersist/0 because consuming was taking too long
Aug 25 12:40:06 dieter-mt2 metrictank[10340]: [Sarama] 2016/08/25 12:40:06 consumer/broker/0 added subscription to metricpersist/0
```

**Comment by woodsaj** [comment]
> consuming was taking too long

too long means more then "consumer-max-processing-time".  The default is 1second. If you increase this, does the problem go away?  

Also note that it appears that we only have a single goroutine consuming from kafka which may be causing problems.  PR #296 changes this to a goroutines per topic:partition.

**Comment by Dieterbe** [comment]
i tried at 60s, problem remains.  will retry this once #296 is merged.

**Comment by Dieterbe** [comment]
bug in sarama. see https://github.com/Shopify/sarama/pull/712#issuecomment-243349746

**Comment by Dieterbe** [comment]
fixed with new sarama lib
