### ISSUE TITLE
indexing metrics: split up update vs add

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#304]
currently the metrics are a bit confusing, due to the memory index receiving continuously new "adds" that are actually updates. and ES not getting any news adds after the initial adds.

**Comment by Dieterbe** [comment]
There's really several problems here:

1) memoryIndex executes updates and adds (but calls both "adds")
2) ES does not perform updates unless partition changes (created #500 for that)
3) ES uses the bulk indexer, so adds, updates and deletes are intermingled and we can't really know how many of each went into each bulkSend (and hence also into each processEsResponse). we can't really track the properties ourselves since elastigo calls bulkSend concurrently. we could do it if we implemented our own bulksender, but that's just not something we should do now since we don't use the es index and we discourage it anyway.

**Comment by woodsaj** [comment]
Personally i think we should just remove the ES index from the code base.  There is no benefit to us keeping it around.

**Comment by Dieterbe** [comment]
yeah that's reasonable. I'll do that in my pr as well.
