### ISSUE TITLE
make tags strings instead of numbers

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#31]
```
(*schema.MetricData)(0xc8201de300)({
 OrgId: (int) 1,
 Name: (string) (len=37) "litmus.localhost.dev1.dns.error_state",
 Metric: (string) (len=22) "litmus.dns.error_state",
 Interval: (int) 10,
 Value: (float64) 0,
 Unit: (string) (len=5) "state",
 Time: (int64) 1443523161,
 TargetType: (string) (len=5) "gauge",
 Tags: ([]string) (len=3 cap=3) {
  (string) (len=13) "endpoint_id:1",
  (string) (len=12) "monitor_id:4",
  (string) (len=14) "collector:dev1"
 }
})
```
just curious, why tags like `endpoint_id:1` and not `endpoint=localhost` ? (the latter would facilicate some search (metrics2.0/graph-explorer style) scenarios where you can search for all metrics with endpoint=localhost etc, or autocomplete/auto-suggest: give me all values for endpoint=local*)

**Comment by woodsaj** [comment]
no real good reason.  Mostly just a relic of previous incarnations.

Changing the code to replace or add additional tags is easy, but in order for users to lot lose access to all of the existing data in kairosdb/cassandra, we would need to perform a data migration. And given we have ~800Gb of data already that would not be a easy task.

**Comment by Dieterbe** [comment]
this is not an MT issue. it is one of the action items on https://github.com/raintank/ops/issues/282
