### ISSUE TITLE
metrictank sharding phase 1

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#315]
the goal is to split up incoming data, to handle more data than what a single node can manage.
it should be fairly linear:  if 1 instance can do X metrics/s ingest and hold Y data in ram, then we should be able to do 20X and 20Y by using 20 MT instances.

for now the idea is to configure a given MT instance with a list of partitions it should consume from.
primary status is still on a per-instance (e.g. set of partitions) level.
in the future we can worry about leader failover, per-partition granularity, automatic cluster management, etc.

note that currently all data for a given org is guaranteed to go into the same partition.
while querying for multiple orgs in 1 http request is uncommon, it is technically possible. (e.g. own org's data along with public data under org -1), so we have to solve the case of single queries requiring data from multiple nodes.
also at some point we'll have to split up data across different nodes for large orgs.

re metricdefinition index, there's 2 approaches:
- shard index as well (e.g. only keep metricdefs in index for the data that we host):
- let's us manage arbitrarily large amounts of metrics, without being limited to RAM size on single nodes.  although index size is not a problem yet and sharding it could wait. but has to happen eventually.
- lookups may be faster, but the only way to leverage this is if you can be sure, for a given query, you don't need to query another instance. this means deducing partitions from input query, and the ability to target queries at the right instances.  implementing that seems far off.
- MT instances must talk to _all_ other instances and have them do lookups in their indices. so in practice lookups are slower.
- note that currently, MT's at startup will load in all defs from cassandra, so we would need a way to save/load indices to/from cassandra respecting the sharding as well.
- full index on each node:
- we could extend the data in the index to mark the corresponding partition for each metricdef. and from that we can figure out if we need to query any other MT instances.
- to do this with sharded data streams we can't keep the current approach of maintaining the index from the data stream. here's 2 ideas:
- when we adopt the separate metadata stream discussed elsewhere, we can have 1 topic that all nodes subscribe to. the metadata stream will become small and mostly contain new values. so low overhead. but with other inputs (e.g. carbon), things become weird
- we could periodically sync updates from cassandra-idx back into ram. this sounds clunky and hard.
- each instance has to do more work to keep the idx up to date, but it doesn't seem that bad (see above)

I need to think about this a bit more.
BTW right now, AJ said per metricdef, the index takes about 1kB.
I believe we can probably reduce this to <= 100B per metricdef, with a more optimized index. but let's go with 1kB.
that means to store 10M metrics we need 10GB. I personally think it's acceptable to trade in more RAM per instance for reduced latency / network bandwith of querying other nodes.
but this won't get us to >100M metrics.

It seems to me network bandwith will be higher if nodes need to query each other for every request, than what the bandwith is to maintain the full index in each node. and also the extra latency of course. Though I suppose instances could also cache the most commonly requested metricdefs from other nodes, which seems to solve this problem.

a request would look something like this:
query idx for all needed definitions / query all other instances for idx lookups (possibly with cache) # still TBD how we'll implement index.
alignRequests sets parameters, taking all definitions into account.
node that got the query pulls in its own data as well as queries other nodes (again) to collect their part of the response
node series together (in the future, extra processing might happen like sumSeries across all series)

in related news, the grpc framework, which a lot of people seem very excited about, recently announced its 1.0 GA status (http://www.grpc.io/blog/gablogpost)
although Brad Fritzpatrick is quoted for saying "the Go grpc code has never yet been profiled or optimized" and the performance of it is currently subpar (https://github.com/golang/go/issues/16844#issuecomment-245261755) though I expect this to change soon.

**Comment by dgryski** [comment]
To some extent this is what carbonzipper solves.

**Comment by Dieterbe** [comment]
another interesting approach would be to move the index into separate processes (that have the entire index in process). those processes would receive the queries, do the index lookups, and know exactly which nodes need to be involved. it can then do alignRequests and involve only the MT's that own that data.

**Comment by woodsaj** [comment]
>note that currently all data for a given org is guaranteed to go into the same partition.
while querying for multiple orgs in 1 http request is uncommon, it is technically possible. (e.g. own org's data along with public data under org -1), so we have to solve the case of single queries requiring data from multiple nodes.
also at some point we'll have to split up data across different nodes for large orgs.

we already need to shard across large orgs now, it is not something we can do later.

**Comment by Dieterbe** [comment]
Right. Not sure what I was thinking. Obviously the need to shard data for large orgs is the point here.

**Comment by Dieterbe** [comment]
re index, I think we can sidestep the "right way", and just do something simple:
instances will consume their share of the data and maintain their index based on data they've seen, but they will store it in "the" (unsharded) cassandra/ES index.
when booting up, an instance will load in the full index from cass/ES, containing the data intermingled from different instances (shards) but that's OK for now.
thus, the MT instances will commonly have lots of metricdefs in their index for which they don't have data. for any query we will query all other instances for their metricdefs and there will be lots of redundancy and instances claiming to have metrics which they don't, but it's ok, we just collect it all, reduce it to unique metricdefs, call alignRequests, and then call each MT instance for all of the metricdefs we're looking for, and those that have it, will return the right data.

there's various inefficiencies in this design but should be good enough to get started and improve later.

**Comment by woodsaj** [comment]
> then call each MT instance for all of the metricdefs we're looking for, and those that have it, will return the right data.

that wont work as all MT instances which are queried for metrics they dont have, will query cassandra.  We need to query only 1 MT for each series in the set.

But we can handle it like this.
1) broadcast the query to all MT nodes, then return the matching metricDefs which include the "lastUpdated" field.
2) reduce the returned series to a unique set, preferring the node that returned the most recently updated metricDef
3) align requests
4) query the MT nodes for the data

**Comment by Dieterbe** [comment]
:+1:

**Comment by Dieterbe** [comment]
#400
