### ISSUE TITLE
pruning of stale metrics from index

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#319]
for customers with high cardinality data, where new series are often created, they want to clean up stale series.
particular goals:
1) don't bother querying mem or cassandra when we know it won't match the condition (e.g. query a series with timestamp >= 24h ago but we know there's no data for a week) e.g. we have a customer who has metrics that are very high cardinality and become useless after about a week [1]
2) don't show targets in responses that are no longer relevant. (i'm adding this one myself, no one has really asked for this)

note that this differs from our current GC mechanism, which can empty out the data for a series in memory, but does not touch the in-memory or persistent idx. so it will not stop queries from requesting series from the mem/cassandra data store. [1]

[1] we could also check the lastUpdate field of the metricdef in the index field, and if that's more recent than the requested timerange, there's no need to query for any data.  this doesn't seem very robust as a node may have just come online, pulled in the latest idx, but not be aware yet of idx changes that another memory is still trying to persist, although we could also address that with some kind of syncing mechanism. but then there's little point keeping the data on the idx.

so i'm not 100% clear yet on whether to implement idx cleaning vs lastUpdate checking, but on the other hand the indices need to be cleaned up *at some point* anyway.  for most customers I suspect this would be after the same time as the retention of the lowest res rollup, and once we have that implemented, we can just switch that to a week for this particular customer.

**Comment by woodsaj** [comment]
I think there are 2 issues that need addressing.

1) not allowing the index to grow indefinitely
2) only return relevant data for queries.

- for 1, i think a configuration option to prune entries from the index that have not been seen for X amount of time.

- for 2, i think that we should handle this through the index searches.   The graphite "metrics/find" query already passes "from" and "until" fields.  So we just need to limit the search to series where last_update > "from - 24h".  This is also relevant for metrics that change interval. Currently when multiple intervals for the same series have been seen, we merge the data sets. However the alignment logic is processed first, which results in the calculated step being set to the largest interval. So if you send data at 60seconds, then start sending at 10seconds then the lowest resolution data your queries will get back is 60seconds (6 points consolidated).

**Comment by woodsaj** [comment]
Both 1 and 2 have been implemented and merged to master.

for 1). If a series has not been seen for the maxStale period, then it is removed from the index.  If a series has multiple metricDefs, ie due to intervalChange, then all defs must be stale for longer then maxStale before the series is removed.  This ensures that when changing interval, you will still be able to access old agreggated data as long as you keep submitting metrics for the series.
