### ISSUE TITLE
why cgo disabled?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#322]
8563f62455ff95b36de95d508ea17af536f716c7
why?
we need cgo to compile with race detector:
```
go build: -race requires cgo; enable cgo by setting CGO_ENABLED=1
```

**Comment by woodsaj** [comment]
cgo is disabled so we build statically linked binaries, thus being more portable.

we should test with -race, but we should not build with -race as it adds a lot of overhead.
