### ISSUE TITLE
expected values missing from render reponse

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#323]
the point at 1474230960 should be present for both series.

```
anthony:~/raintank/raintank-docker/raintank_code/k8/snap_k8s$ curl -s -H "X-Org-Id: 20732" http://10.240.0.42:18763/render -X POST --data "target=worldping.grafana_net.{new-york,tokyo}.https.total&from=1474230913&until=1474231200&format=json&maxDataPoints=1920"|json_pp
[
   {
      "target" : "worldping.grafana_net.new-york.https.total",
      "datapoints" : [
         [
            3647.196,
            1474230960
         ],
         [
            null,
            1474231020
         ],
         [
            318.562,
            1474231080
         ],
         [
            293.86,
            1474231140
         ],
         [
            230.222,
            1474231200
         ]
      ]
   },
   {
      "target" : "worldping.grafana_net.tokyo.https.total",
      "datapoints" : [
         [
            null,
            1474230960
         ],
         [
            960.586,
            1474231020
         ],
         [
            895.53,
            1474231080
         ],
         [
            922.086,
            1474231140
         ],
         [
            880.344,
            1474231200
         ]
      ]
   }
]
```

interestingly, the point is returned with the TS is between (inclusive) 1474230900-1474230912  but it is null when the TS is between 1474230913 - 1474230959

**Comment by woodsaj** [comment]
This issue has resulted in worldping alerting to be broken for a while, as alerting requests the last N values and checks to see if there are N consecutive values above 0.  But as the first value returned is null,   the condition of N consecutive values is never met.

I have been able to work around this by having worldping quantize the the "from" time to the check frequency.  https://github.com/raintank/worldping-api/commit/c565e3a5581ede8df3baf6bdc1572813cedfb351


So there is something wrong with how we quantize the values.

I am fairly confident that this is what is happening, but i havent looked at the code yet.

Assuming points are sent every 60seconds at an offset of 5seconds( eg at 5, 65, 125)

As we quantize the values in the response, a request with a range of FROM=0,UNTIL=120 should return 2 points (60, 120), these two points would correspond to the real values (5,65).
If the request range is FROM=10,UNTIL=120 then we should still get 2 points (60,120).  However this is where the problem is occurring, these two quantized points map to the same (5,65) values stored. But due to "5" being less then the from range it is excluded, so instead the result is (null, 120)

**Comment by nopzor1200** [comment]
I think this is the issue responsible for uber ticket 793? If so this is a pretty big deal.

**Comment by nopzor1200** [comment]
I guess not, I see your comment re: work around @woodsaj

**Comment by Dieterbe** [comment]
> However this is where the problem is occurring, these two quantized points map to the same (5,65) values stored. But due to "5" being less then the from range it is excluded, so instead the result is (null, 120)

this assessment is very likely to be correct. i can probably whip up a test case to confirm.
we could fix it by querying for data from `from - interval`, then calling fix (quantisation), and only after that, trim off points as needed.
