### ISSUE TITLE
null values become 0

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#36]
in the dashboards, when probe errors on http requests, it still shows 0ms in the UI, even with "null as null" set.

what's probably happening is that the probe does report nulls but the schema initializes float64's to 0

**Comment by woodsaj** [comment]
https://github.com/raintank/raintank-metric/blob/master/schema/metric.go#L21  this need to be a *float64

**Comment by Dieterbe** [comment]
not necessarily. apparently within float's you can encode NaN (null) values.
see
https://golang.org/pkg/math/#NaN
https://golang.org/pkg/math/#IsNaN

**Comment by Dieterbe** [comment]
@woodsaj looks like this has been fixed in the collector already?
with nsq_metrics_to_stdout in devstack i can see no more metrics come in as soon as i make the http monitor fail.
(and by extension, no bad 0ms points show up in grafana)

**Comment by woodsaj** [comment]
Yes, the collectors have been configured to just not send nulls.  

Though i still think we need to be able to handle null values.   The current problem is that a when unmarshaling from json, null is converted to 0 and not to Math.NaN().

**Comment by Dieterbe** [comment]
@woodsaj do you think this is still a problem anywhere?

**Comment by woodsaj** [comment]
Not in anything i am aware of. But you might want to make sure carbon-relay-ng doesnt try and send nulls.

**Comment by Dieterbe** [comment]
cool. it doesn't.
