### ISSUE TITLE
whisper to MT/cassandra tool

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#379]
we need to ease the process for people who want to migrate.
I think we need a tool that can read in whisper files and convert to tsz data into cassandra, there isn't really a need or benefit of going through a MT daemon.
* the raw data should be fairly straightforward 
* rollup archives to cassandra aggregated series. note: whisper only has let's you configure 1 rollup function per series, need to check if we can gracefully support this (e.g. show a proper warning if people ask for consolidation that was not in the data)

**Comment by Samaelson** [comment]
any news about this?

**Comment by Dieterbe** [comment]
No news yet sorry.

**Comment by Dieterbe** [comment]
we have this almost ready : #533

**Comment by Dieterbe** [comment]
merged.
