### ISSUE TITLE
go vet errors due to use of unkeyed struct literals

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#388]
`go vet` ensures that best practices are used within the code.  It should always pass.

**Comment by Dieterbe** [comment]
I disagree with this.  sometimes go vet's heuristics will lead to poor recommendations. 
like in our case being forced to use `schema.Point{Val: 0.5, Ts: 1234567890}` over `schema.Point{0.5,1234567890}` is not an improvement. it adds verbosity for no good reason IMHO.

**Comment by Dieterbe** [comment]
Although there's quite some value with the other go vet recommendations so maybe that's just the price to pay

**Comment by woodsaj** [comment]
`schema.Point{Val: 0.5, Ts: 1234567890}`  I would not call an additional 7 characters overly verbose.

If you don't want to have to keep typing field names, then just add a constructor so you can call `schema.NewPoint(0.5, 123456789)`  

```
	aggSettings := []mdata.AggSetting{
		{600, 21600, 1, 0, true},
		{7200, 21600, 1, 0, true},
		{21600, 21600, 1, 0, true},
	}
```

this is a good example where field names should be used.  The first four fields are all uint32. If the ordering of the fields were changed the code would still compile but would get very weird results which would be hard to track down.
