### ISSUE TITLE
remove branch vs leaf node restriction in index

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#392]
current index does not allow node to be both leaf and branch. (graphite has the same restriction)
which for some customers is an annoyance.

me:
 i think we can improve on the graphite model in a backwards compatible way, by allowing to change leaf nodes in some sort of special mode that holds a metricdef, but also has children. graphite has the restriction because of the whisper background, where you can't have a file and a directory with the same name, but we could have a node in the index that can have both data (metricdef) as well as children

[4:07] ￼
I think this will make our product more userfriendly and applicable to more different usage patterns

AJ:
sounds good.  Plus it is another benefit  of Metrictank over Graphite/whisper

**Comment by woodsaj** [comment]
I think we should prioritise fixing this as it looks like graphite does support having combined leaf and branch nodes.  You just can see it when using the graphite tree browser https://github.com/graphite-project/graphite-web/issues/193
