### ISSUE TITLE
facilitating cache warmup / caching cassandra data

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#401]
when MT starts up, its in-memory cache is cold, so we hit cassandra a lot more and queries get slow.
you can load older data from kafka (which mostly works, see #309) which has its uses (e.g. recovering a failed primary) but if the goal is to simply fill up the memory chunks, then it's not a very efficient solution (decoding metricdata, generating the tsz data cost cpu, and the data in kafka is very bloaty. also if the node is primary it'll needlessly overwrite existing data in cassandra etc, posibly overwrite full chunks with partial chunks even)

in theory, in this scenario (e.g. when we hit cassandra over and over again for the same recent chunks) cassandra nodes just return chunks of data that is in linux' block cache, and so it should be cheap (just some networking and java code overhead, since most of the slow paths are bypassed)
I don't understand cassandra well enough to know how close to reality this is, and maybe with a better tuned cassandra and cassandraStore this issue becomes much smaller.

Either way, I think a basic form of caching is in order.

here are some bad ideas:

* query cache -> queries from/to will always be slightly different, so this would have a tiny hit ratio
* caching of decoded go-tsz chunks -> go-tsz decoding takes time but is not the main bottleneck now, but could be interesting later. would take up lots of memory however.

here are some better ideas:

1) have a cache that caches chunks fetched from cassandra. not sure on cache policy yet (LRU vs frequency vs [frecency](https://en.wikipedia.org/wiki/Frecency). also worth noting that chunks containing more recent data will be more likely to remaining in the query windows for longer.
2) same as 1, but instead of a separate chunk cache, we would put the chunks into the aggmetrics structs.  e.g. if you have numchunks 30 but due to a fresh start there's only 5 chunks in RAM, we can fill in the remaining 25 when we happen to fetch them from cassandra.  and so the numchunks becomes the deciding factor on whether to cache or not. (if this implementation would become too complex, we can still do a separate cache, but just use the numchunks*chunkspan window as cache policy)

I like 2 especially because the reason we choose a specific numchunks is because we expect that amount of chunks to be queried a lot.

at this point it's worth pointing out though that our current approach of applying the same `numchunks` to all series is also suboptimal. some of them may be never queried, while others need to be decoded over and over again. (not currently a bottleneck, but if we removed 80% of unqueried chunks, we could keep the decoded data in ram for those chunks that are queried over and over again)

But I think we could probably implement 2 for now as it is low hanging fruit, and do further optimizations later.

**Comment by Dieterbe** [comment]
thought a bit more about it. changed my opinion.
i think trying to cache chunks by adding into aggmetrics' ringbuffer is unneccesary complication, especially when we know the "just cache all series for numchunks" strategy is naive and inefficient.
instead, I think we should just do a simple chunk cache, perhaps in cassandraStore, detached from AggMetrics.  and we should minimize numchunks as much as we can (e.g. use 1 or 2) and just let the cache do all the work of keeping the chunks in memory that are queried for. this will result in higher hit ratios and more efficiency.
I think it's trivial to implement a basic cache and there will be a lot of benefits:
* we will reduce the cassandra load, probably significantly reduce or remove the timeout problems
* many of the queries will return faster
* we can reduce warmup time for a new node (no more fear that a short warmup will overload cassandra)


configuration will also be simple, instead of working with a static numchunks, which causes varying RAM usage depending on how many series there are, and hence is hard to configure to make good use out of the available ram, we can configure an actual max cache size, or we can even have metrictank monitor its own RAM usage and tell it to size the cache so that at all times we leave X GB ram to the rest of the system.

I'm pretty excited about the ROI here. I think optimizing mem vs cassandra hit ratio is long overdue.
let's tackle this after clustering and metrics refactor, @woodsaj , @OOM-Killer 
though we should start with instrumenting hit/miss ratio metric and collect some more data in our various envs

**Comment by woodsaj** [comment]
I think this makes sense and would be a great improvement.

So i think this is best implemented by having a 3 tiers of storage.
1) aggmetrics:   This is required to serve data from the chunk that is currently being populated.
2) chunk Cache:  Consumes majority of memory and is effectively a query cache.
3) cassandra:

This will allow us to simplify Aggemtrics so that we no longer need a ring buffer and instead only track the active chunk.  When the chunk is closed, we just push it to the cassandra_store write queue and check if the specific series is already in the "Chunk Cache" (indicating it is likely being actively queried) and if so then add this new chunk to the cache.

I think this will provide significant benefits to query speed as we will be able to store much large time windows in memory due to only needing to cache actively queried data.

**Comment by Dieterbe** [comment]
done via #417
