### ISSUE TITLE
use cassandra idx by default in all configs, make it the "preferred" idx

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#412]
is there any use for the in-memory-only index? seems like it can be confusing and cause harm. people can get confused about why the data is in cassandra but metrictank doesn't know about it after a restart.

especially since data is always stored in cassandra, we may as well default to the cassandra index and remove the in-memory-only option.
cc @replay 

thoughts @woodsaj ?

**Comment by replay** [comment]
I guess the big advantage of the in-memory index is that it's faster than the cassandra backed one. 

I'm assuming the chunk cache from #401 would only be used for data chunks and has nothing to do with the cassandra backed index, right? 

Maybe it would  be better to not completely delete the in-memory index, but instead write to both the memory index and the cassandra index, but only read from the memory index (for speed). Then on restart of metrictank the memory index could be rebuilt from the cassandra index.

**Comment by woodsaj** [comment]
Both the ES and Cassandra indexes use the MemoryIdx for handling queries.  At startup, the index is read from either ES or cassandra and loaded into memory.  When new metrics are seen they are added to the MemoryIdx and also the the ES or cassandra backend as well.

I dont think we should prevent users from using just the MemoryIdx, but i do think we should make the default the cassandra Index.
