### ISSUE TITLE
cant set primary to false via /node endpoint

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#431]
Primary can only be set to true.

get the error
`[{"fieldNames":["Primary"],"classification":"RequiredError","message":"Required"}]`

this is because the "primary" field is set to required.  But the validation library treats the zero value the same as the value not being defined.

**Comment by replay** [comment]
if `false` is equal to the zero value, wouldn't it make sense to just not define `primary` as a required field and if it isn't specified then it will be set to `false`?

**Comment by replay** [comment]
I went ahead and pushed a change that requires this to be specified via string.
