### ISSUE TITLE
fix default cassandra keyspaces

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#438]
* for idx, all config files/docs say he default is `raintank`, but the code uses `metrics` as default (!)
* for cassandraStore, we use `raintank` by default`

I have not checked the cookbook

I think we should just use `metrictank` as default keyspace for both. (e.g. in code, in all configs, in the docs and in the cookbook)

thoughts @woodsaj @replay ?

**Comment by woodsaj** [comment]
I agree, 'metrictank' seems like the sane default.
