### ISSUE TITLE
0.7.0-beta1

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#443]
There's a lot of new stuff coming up that will need to see some real production usage before we can slap a stable release tag on it. so here's how i see things:

## 0.7.0-beta1
* once chunk-cache, metrics refactor, etc are merged
* what should the tag be? will `0.7.0-beta1` work? (wrt that version being applied to the deb and rpm packages, version ordering by different package managers etc).  @torkelo @bergquist do you have advice on this?

## 0.7.0
to be released after having run the beta's in prod for a while, made any needed adjustments to code, the metrics hierarchy, etc. and we consider it stable.

**Comment by bergquist** [comment]
0.7.0-beta1 should work with debian and centos.

**Comment by woodsaj** [comment]
we already build packages for Debian (Wheezy and Jessie) Ubuntu (Trusty and Xenial) and Centos (6 and 7)

**Comment by Dieterbe** [comment]
i tagged db109617a316d45050945b8345b95866ce21d26e as 0.7.0-beta1 (annotated tag) but circleci is not picking it up for some reason: `GITVERSION=0.6.0-185-gdb10961`

will investigate later.

**Comment by Dieterbe** [comment]
0.7.0-beta1 is out now. :)
