### ISSUE TITLE
"start must be before end" when requested time range is correct

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#454]
I am seeing this frequently when querying against the new 0.7.0-beta1 version of MT.

```
curl -H "X-org-id: 12574" "http://localhost:6060/render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416"
```
```
[Macaron] 2017-01-08 01:23:56: Started GET /render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416 for 127.0.0.1
2017/01/08 01:23:56 [I] HTTP Render: INCOMING REQ "GET" from: "1483795216", to: "1483838416" targets: ["metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32"], maxDataPoints: 800
2017/01/08 01:23:56 [I] oldest from aggmetrics is 1483833600
2017/01/08 01:23:56 [graphite.go:284 renderMetrics()] [E] HTTP Render start must be before end.
[Macaron] 2017-01-08 01:23:56: Completed /render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416 500 Internal Server Error in 582.581µs
```

As the error is intermittent is suspect it has something to do with handling partially cached data.
The error looks to be originating from:
https://github.com/raintank/metrictank/blob/master/api/dataprocessor.go#L467-L470
We should definitely log an Error here before calling panic.

this panic is handled by https://github.com/raintank/metrictank/blob/master/api/dataprocessor.go#L29
Which is why we dont get the usual stack trace.

**Comment by replay** [comment]
That's an interesting one, I agree it's probably related to partially cached data. I'll read through the related parts one more time trying to figure out what's going on, but I think it might make sense to add a mechanism which dumps the current state of the cache and aggmetric for that metric in order to be able to properly reproduce it.

**Comment by replay** [comment]
At the time when this happened, would it be possible that these chunks that have been queried were written by an MT version that did not have the PR #418 (to include the spans in the chunks) yet? In my local test env I've done all kinds of queries, using curl, where I intentionally created fragmented linked lists in the cache, some with and some without gaps between, and then queried them over various ranges. Basically I tried all scenarios that I could think of which would be hard to handle and which might lead to bugs in stitching the pieces together. The PR #455 still brings clear improvements compared to not having it, but even without it i was not able to reproduce the error you posted.
The only scenario I've left that I can think of right now is that these chunks were not span aware, so they must have been written in the old chunk format. If you think that's possible I'll setup another MT which writes non-span-aware chunks and then I query them with `0.7.0-beta1`.

**Comment by woodsaj** [comment]
i dont think so but it should be easy enough to grab the chunks out of cassandra and check.
