### ISSUE TITLE
Add new chunks to cache if metric is hot

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#457]
If a chunk gets persisted and we know that it's metric is "hot" meaning it's queried often we want it to get pushed into the cache. That way we can save one trip to Cassandra which would be necessary to retrieve it again and push it into the cache. It is important though that we don't push "cold" chunks into the cache because we don't want to evict important stuff in exchange for something we don't need.

**Comment by replay** [comment]
I just noticed that if our production setup has separate read and write nodes, this change is only useful to us if the read nodes replaying the kafka logs also push the chunks of hot metrics into the cache that they would persist if they were primaries.

**Comment by replay** [comment]
I think this looks good for a start. 
Notice that:
- Chunk span is 1min
- There's a `chunk push` metric which indicates when a chunk got cached at persist time because it's metric was considered hot
- There are no misses/partial hits, all hits are full hits

![screenshot from 2017-01-09 22-51-43](https://cloud.githubusercontent.com/assets/195371/21786905/389e43c2-d6be-11e6-9885-ef32f6bfc687.png)

**Comment by Dieterbe** [comment]
cool i like the push metric :)

**Comment by Dieterbe** [comment]
> I just noticed that if our production setup has separate read and write nodes, this change is only useful to us if the read nodes replaying the kafka logs also push the chunks of hot metrics into the cache that they would persist if they were primaries.

this is always the case, right?.  given the same input stream, primaries and secondaries will add data to aggmetrics and their chunks and call `persist()` the same way and at the same times. it's just that for secondaries, persist will not call `store.Add`, but that should be independent of adding to the cache.
not sure if i'm just restating what you already know or said, or am i missing something?

**Comment by Dieterbe** [comment]
fixed by #461
