### ISSUE TITLE
better handling of raw interval > agg-interval

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#464]
we have a customer that runs with agg-settings `10min:6h:2:38d:true,2h:6h:2:120d:true`

however, much of the data comes in at 1d intervals.
it's silly to create rollup archives at lower resolutions for those metrics (needless resources), but worse, I believe the generated rollup series would have chunks with only 1 point and many many nulls, which doesn't make sense.

#382 should probably not be implemented on a raw vs aggregated basis, but on a per-interval data. (e.g. data at 1d interval should go in a table optimized for that, whether it's raw or aggregated).
this would also let us apply a fair TTL to the raw but very coarse data.

also, will have to check alignRequests, and makes sure it behaves as expected for this scenario.

**Comment by woodsaj** [comment]
I think the better solution is to allow perSeries aggregation policies like carbon does.  ie, regex matching to get the correct aggregation policy.

The table changes suggested in #382 are based on the ttl of the metric/chunk (the chunkspan doesnt matter) and are intended to control the number of sstables and improve delete efficiency.

 ie
If data is stored for 1week (ttl=1week), then we want to use daily sstables giving us 7sstablse on disk.  Once we have 8 sstables, we know that all data in the oldest sstable is past the 1week ttl and we can just delete the entire sstable.

If data is stored for 3months (ttl=3months), then we want to use weekly sstables giving us 12 sstablse on disk.  Once we have 13 sstables, we know that all data in the oldest sstable is past the 3month ttl and we can just delete the entire sstable.

**Comment by DanCech** [comment]
I agree, a single set of aggregations system-wide is definitely a big limitation and will always lead to extra data being stored unnecessarily.

**Comment by Dieterbe** [comment]
multiple aggregation rules with matching patterns is on the todo list. And though it helps solve this problem, it doesn't rule it out. There's always a chance the rules aren't properly configured or become out of date.  We could do more: for example when new AggMetric is created (eg new series data comes in) we can forego instantiating rollups that have interval <= interval of the raw data. and we could extend the TTL of the raw data to the longest TTL found amongst rollup rules that have an interval <= raw interval.

pro:
- seems trivial to implement
con:
- it's not what graphite does

**Comment by Dieterbe** [comment]
>  We could do more: for example when new AggMetric is created (eg new series data comes in) we can forego instantiating rollups that have interval <= interval of the raw data. and we could extend the TTL of the raw data to the longest TTL found amongst rollup rules that have an interval <= raw interval.

this is now implemented via #588 and 764c7fa8c5f591913db94198ca4253bf98b39f4a
