### ISSUE TITLE
Cassandra-idx load timeout

### ISSUE THREAD

**Issue by ehlerst** [raintank/metrictank#471]
When loading metrictank you may get the error:

`
[cassandra.go:289 load()] [E] Could not close iterator: Operation timed out - received only 0 responses.`

The way this works as i understand is when metrictank starts the metrics in metrictank.metric_idx are loaded. This query can get very large and no matter how much horsepower you throw at it the query may end up over 1second. You can adjust the timeout on metrictank index from 1s to inf however Cassandra itself usually has a default timeout as well:

`
request_timeout_in_ms: 10000
read_request_timeout_in_ms:10000
range_request_timeout_in_ms:10000`

Adjusting these to something very high should be OK since metrictank itself has query protection.

**Comment by ehlerst** [comment]
Adjusting to the extremes 5 min timeouts the index wont load.

`2017/01/13 17:49:20 [cassandra.go:289 load()] [E] Could not close iterator: gocql: no response received from cassandra within timeout period

real	4m12.149s
`
This is running:
metrictank-0.7.0_beta1_28_gdc95a22-1.x86_64

If i truncate i can connect, here is what the table metrics look like:
```
		Table (index): metric_idx.metric_idx_partition_idxmetric_idx.metric_idx_partition_idx
		SSTable count: 3
		Space used (live): 109140348
		Space used (total): 109140348
		Space used by snapshots (total): 0
		Off heap memory used (total): 15080
		SSTable Compression Ratio: 0.8880139996906262
		Number of keys (estimate): 1
		Memtable cell count: 0
		Memtable data size: 0
		Memtable off heap memory used: 0
		Memtable switch count: 0
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 0
		Local write latency: NaN ms
		Pending flushes: 0
		Percent repaired: 0.0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 48
		Bloom filter off heap memory used: 24
		Index summary off heap memory used: 48
		Compression metadata off heap memory used: 15008
		Compacted partition minimum bytes: 10090809
		Compacted partition maximum bytes: 62479625
		Compacted partition mean bytes: 42218316
		Average live cells per slice (last five minutes): NaN
		Maximum live cells per slice (last five minutes): 0
		Average tombstones per slice (last five minutes): NaN
		Maximum tombstones per slice (last five minutes): 0
		Dropped Mutations: 0
```

**Comment by woodsaj** [comment]
@ehlerst this should be fixed by https://github.com/raintank/metrictank/pull/465

**Comment by tehlers320** [comment]
i threw #465 into our test lab (~3.5 million active datapoints). Will restart it tuesday let you know how it goes.

**Comment by ehlerst** [comment]
i threw #465 into our test lab (~3.5 million active datapoints). Will restart it Tuesday let you know how it goes.

**Comment by ehlerst** [comment]
Gave it a bounce this afternoon and it still times out. I see a ton of merges, trying again with the latest.

**Comment by woodsaj** [comment]
@ehlerst you will need to delete/recreate the cassndara metric_idx table as the schema has changed.

**Comment by Dieterbe** [comment]
yeah metrictank only applies the new schema if the table doesn't exist yet.

**Comment by ehlerst** [comment]
Yeah i thought about that yesterday when i launched the latest master. I dropped the keyspace this time. The issue still occurs. 

here is what is in the schema:

```
CREATE TABLE metrictank.metric (
    key ascii,
    ts int,
    data blob,
    PRIMARY KEY (key, ts)
) WITH CLUSTERING ORDER BY (ts DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'DAYS', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

cqlsh> describe metrictank.metric_idx;

CREATE TABLE metrictank.metric_idx (
    id text,
    partition int,
    interval int,
    lastupdate int,
    metric text,
    mtype text,
    name text,
    orgid int,
    tags set<text>,
    unit text,
    PRIMARY KEY (id, partition)
) WITH CLUSTERING ORDER BY (partition ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE INDEX metric_idx_partition_idx ON metrictank.metric_idx (partition);
```

The only major difference i have from the test setups you have is that i'm on cassandra 3.9 

The cluster is currently 3x r3.xlarge in the past i tried scaling the cluster as high as 6x c3.4xlarge and it still would not start. System load on cassandra in all cases ramps up to the high 20s. Ill try resizing to bigger instances again to see if some amount of processing power lets it startup.

**Comment by Dieterbe** [comment]
that's still the old schema. are you sure you run the latest version and removed the old table?
see 77ad8d40c13d41bb4fd1c880cebf4797ae4bfe0b for the change

**Comment by ehlerst** [comment]
Awesome.. I've never compiled go before i sorted out my error, i didn't understand how the deps were pulled down or not pulled down again with the go get command.... I was able to restart after a short run with metrictank (built with go1.6.3, git hash 0.7.0-beta1-67-ge380194)

**Comment by Dieterbe** [comment]
note that you can also install packages from https://packagecloud.io/raintank/raintank, those are the latest master builds.  see also https://github.com/raintank/metrictank/blob/master/docs/installation.md
