### ISSUE TITLE
Metrictank selects aggmetric without taking TTL into account

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#503]
When querying metrictank it selects the best aggmetric to serve a request based on the time range that's been queried, but it ignores whether the requested times are recent or long ago. This results in the following scenario:

- I query a short time range (f.e. 10 days) where the `to` is long ago (f.e. 1year)
- metrictank sees that the queried range is 10 days and it sees the requested max datapoints, based on that it selects an aggmetric with relatively high granularity
- due to the fact that the requested times are already 1 year ago, the high granularity aggmetric is already beyond it's TTL and hence has no data anymore. At the same time another one with lower granularity would still have data for that time

example:
![screenshot from 2017-01-26 14-08-26](https://cloud.githubusercontent.com/assets/195371/22334516/014572fc-e3d3-11e6-8e3c-884f2ceb2c08.png)

**Comment by woodsaj** [comment]
see als #463
