### ISSUE TITLE
metrictank install script broken 

### ISSUE THREAD

**Issue by pratikp09** [raintank/metrictank#516]
The install script mentioned in the installation document is broken

curl -s https://packagecloud.io/install/repositories/raintank/raintank/script.rpm.sh | bash yum install metrictank graphite-metrictank

It is throwing the below error 
`
/usr/bin/yum: line 2: import: command not found
/usr/bin/yum: line 3: try:: command not found
/usr/bin/yum: line 4: import: command not found
/usr/bin/yum: line 5: except: command not found
/usr/bin/yum: yum: line 23: syntax error near unexpected token `('
/usr/bin/yum: yum: line 23: `""" % `(sys.exc_value,` sys.version)'
`
I tried to fix it but nothing is working.

**Comment by Dieterbe** [comment]
what distribution are you installing on?

**Comment by pratikp09** [comment]
I am installing on RPM based

**Comment by tehlers320** [comment]
The command is missing a ; 

`curl -s https://packagecloud.io/install/repositories/raintank/raintank/script.rpm.sh | bash; yum install metrictank graphite-metrictank -y`

**Comment by Dieterbe** [comment]
note that the instructions contain the commands as separate lines
https://github.com/raintank/metrictank/blob/master/docs/installation-rpm.md#short-version
i confirmed that when i copy paste them (at once) into my terminal, the newline is honored and they are executed as two separate commands. so not sure how it went wrong for you.
