### ISSUE TITLE
provide improved http request metrics

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#545]
Per endpoint metrics

for each
- getdata
- index/find
- index/list
- index/delete
- index/get
- render
- metrics/find
- metrics/index.json
- metrics/delete

collect
- request latency
- request rate per status code 2xx,4xx, 5xx

for graphite queries
- number of series (after searching the index)
- number of points needed for each query (computed from series * time range / selected interval)

**Comment by replay** [comment]
This sounds extremely useful. What would be helpful related to the chunk cache efficiency is how many series are active but have gaps in the data cassandra.
