### ISSUE TITLE
when writing old data, we hammer cassandra index with metricdef updates

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#561]
we set the LastUpdate field based on the timestamp of the data, but compare it against wall clock time.
so if a user creates a new series, and starts writing data from a month ago until now, or when writing data just generally lags behind current clock time by more than 2*updateInterval, we will constantly update the index (both in memory and cassandra) with every point that we receive.

maybe something to think about when working on #559

**Comment by Dieterbe** [comment]
some ideas:
1) we could keep track of the number of points too since we last updated cassandra. and only update if $lastUpdate-time-clause AND update was at least X points ago
2) compare LastUpdate against timestamp of current point, not against wall clock time.

**Comment by woodsaj** [comment]
closed by https://github.com/raintank/metrictank/pull/574
