### ISSUE TITLE
MT mdata config validation should ensure proper fit of point resolution into chunkspan

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#578]
chunkspan > interval
and also even fit without remainder. (maybe not strictly needed but seems like a good idea)

**Comment by woodsaj** [comment]
this is tricky, as we have a few users who send really low resolution data, ie once a day. It would not make sense to have to replay more then that at startup.

**Comment by Dieterbe** [comment]
i don't recall what was the original problem that led me to create this ticket, but you're right about very low res data, and also i believe our storage-schemas.conf approach generally makes sure to configure proper chunkspans for given resolutions, so i think we can close this.
