### ISSUE TITLE
mt-import does not re-use socket causing "too many files open" error

### ISSUE THREAD

**Issue by tehlers320** [raintank/metrictank#581]
To reproduce

NOTE: with -verbose the pid slows down enough that it functions 
```
ulimit -n 10000
echo 10 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle

 ./mt-whisper-importer-writer -verbose=true  -http-endpoint=localhost:1234  -cassandra-addrs=10.0.1.0:9042 -cassandra-keyspace=metrictank -exit-on-error=true -fake-avg-aggregates=true -ttls=7d,60d,1y 
 ./mt-whisper-importer-reader  -whisper-directory="/data/graphite/storage/whisper/" -http-endpoint="http://localhost:1234" -exit-on-error -threads 1

```

netstat -an |grep 1234 |wc -l
532
netstat -an |grep 1234 |wc -l
1285
and so on until it runs out of file handles

This is not urgent as the tools work as long as you use -verbose

**Comment by replay** [comment]
Thx for the report @tehlers320. I'll take a look at that

**Comment by replay** [comment]
I think this should fix it. If you don't mind could you confirm it please?

https://github.com/raintank/metrictank/commit/904eb3c4988b55cd6508162411d9f274e5379c78

**Comment by tehlers320** [comment]
Nope, still thousands in time-wait from both pids.

```

sudo netstat -antp |grep 1234  |awk '{print $NF}' |sort |uniq -c
    233 -
   3386 125185/./mt-whisper
   3378 38514/./mt-whisper-
seconds later..
netstat -an |grep 1234 |wc -l
24271

```

I set my ulimit to 100000 but canceled the run. 

I also set these back to default "0" and re-ran with the same result.

```
echo 0 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 0 > /proc/sys/net/ipv4/tcp_tw_recycle
```

**Comment by tehlers320** [comment]
with tw_reuse/recycle at default the time_waits are gone they instead are all established.

```
 netstat -antp |grep 1234  |grep EST |wc -l
14939
```

**Comment by replay** [comment]
ok, i'll investigate why that doesn't reuse the conns. i don't think `tw_reuse` or `tw_recycle` are the appropriate solution for this problem because afaik they just make the OS reuse connections that from an application point of view have been closed, but what we actually want is for the application itself to reuse the connections. i'll dig into it

**Comment by woodsaj** [comment]
https://groups.google.com/forum/#!search/golang$20json$20decode$20$20io.Copy/golang-nuts/4Rr8BYVKrAI/ZrJJFTNleekJ

So you need to call  `io.Copy(ioutil.Discard, resp.Body)` before you close the response.
https://github.com/raintank/metrictank/blob/5eea09788c3e37e73ac550fb8bc3b8619c822b99/cmd/mt-whisper-importer-reader/main.go#L182

Thought looking at this code, you also need to check the response status code.  If the statusCode is != 200, then the payload was never delivered.

**Comment by replay** [comment]
I've setup a test env where i can track if the conns are getting leaked or not. For a reason I don't understand just reading and closing the body doesn't seem to be enough, I also need to manually instantiate the client's `Transport` to make it reuse the connections properly.
@tehlers320 if you don't mind, could you please try again now?

**Comment by tehlers320** [comment]
@replay sorry was there another branch to test?

**Comment by replay** [comment]
@tehlers320 ah, yes, sorry for not specifying it above: https://github.com/raintank/metrictank/tree/whisper-importer-reuse-conns

**Comment by tehlers320** [comment]
@replay This still happens but i think we overlooked something.

-http-endpoint="http://localhost:1234" should be ->
-http-endpoint="http://localhost:1234/cluster"

This works without the proposed merges here. I always create my own problems. I wonder however why its not kicking back an error when you use an invalid endpoint?

**Comment by tehlers320** [comment]
The writer could also use a timeout adjustment.

`{2017/06/21 16:04:06 http: panic serving 10.1.1.1:37830: Error in query: "gocql: no response received from cassandra within timeout period"`

whats weird is 10.1.1.1 is the load balancer, not cassandra i have no idea how the writer got this IP. Is it looping back to its own API and calling itself cassandra?

**Comment by tehlers320** [comment]
I think the core of this bug was me not putting /cluster on the end of the config. 
Fixing that and using #704 this ran successfully for me. I think this should be closed with #704s merge.
