### ISSUE TITLE
prevent multiple MT instances in a cluster from creating cassandra keyspaces

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#605]
having multiple MT instances try and create the cassandra keyspaces can lead to problems in a cassandra cluster.

We need to add "createKeyspace" flag for cassandra_store and cassandra_Idx.

if the flag is true (default) then the instance should ensure the the keyspace and tables exist.
If not true, then we should just check to see if the keyspace and tables exists.  Probably best to repeatedly check until the tables are present with a hard timeout leading to a failure/panic.

**Comment by jtlisi** [comment]
This should be all set with #716
