### ISSUE TITLE
timestamp shifting

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#633]
this is a new issue reported by a customer.
possibly related to the recent changes ~ using graphite-web instead of graphite-api.
as you can see below we have hourly points, but they are reported at a timestamp that is detached from their original timestamp, when you refresh their timestamps update to be more recent, effectively keeping the points at the same place on the plot, but only moving the grid behind them.
![a](https://cloud.githubusercontent.com/assets/20774/25878420/8fd37ffc-34f8-11e7-80f7-38c5f43200b2.png)

**Comment by Dieterbe** [comment]
for example, loading the data at 20:49:26 EDT gives json data like:
```
[{"target": "foo", "datapoints": [[346773.0, 1494334158], [383218.0, 1494337758], [416453.0, 1494341358], [439106.0, 1494344958], [499644.0, 1494348558], [523803.0, 1494352158], [458359.0, 1494355758], [952898.0, 1494359358], [838278.0, 1494362958], [null, 1494366558], [null, 1494370158], [null, 1494373758]]}]
```
the last timestamp is:
```
~ ❯❯❯ date -d @1494362958
Tue May  9 16:49:18 EDT 2017
```

**Comment by woodsaj** [comment]
This is probably due to https://github.com/raintank/metrictank/blob/master/api/models/series.go#L75-L76
the start,end should be set to:

```
var start uint32
var end uint32
if len(s.Datapoints) > 0 {
  start = s.Datapoints[0].Ts
  end = s.Datapoints[len(s.Datapoints)-1].Ts
} else {
  start = s.QueryFrom
  end = s.QueryTo
}
```
