### ISSUE TITLE
aliasSub legend name incorrect when preceeded by sumSeries function

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#648]
can be seen when comparing topleft chart between regular MT dashboard (works fine, has no extra sumSeries) vs MT k8s cluster (has extra sumSeries):

```
aliasSub(perSecond(metrictank.stats.$environment.$instance.input.*.metric_invalid.counter32),'.*\.([^\.]+)\.metric_invalid.*', '\1 metric invalid')
=> 3 entries with name 'kafka-mdm invalid' (correct)

aliasSub(sumSeries(perSecond(metrictank.stats.$environment.$instance.input.*.metric_invalid.counter32)),'.*\.([^\.]+)\.metric_invalid.*', '\1 metric invalid')
=> creates a name '* in' (i don't believe graphite does this)
```

this bug may also affect other functions like aliasByNode.

**Comment by Dieterbe** [comment]
actually what graphite does is not correct either. it's a bit harder to reproduce because we use the kafka-mdm input everywhere and nothing else, but let's pretend the instance name is the name of the input, so that we have some variety, which lets me highlight the problem in graphite. 

so what graphite does in this case, it'll just take the name of the last series, and use that in the aliassub.
this is confusing, because other series with different names went into the sumSeries !
![1-how-graphite-does-it](https://user-images.githubusercontent.com/20774/27481165-82dcb9da-581b-11e7-8dd7-907edce6b653.png)
what MT does is just show `*` which is not like graphite, but now that I think about it, more clear that different series went into the result
![2-how-mt-does-it](https://user-images.githubusercontent.com/20774/27481166-82e2ea62-581b-11e7-9846-9b6127698ff0.png)

**Comment by Dieterbe** [comment]
let's do the same experiment, but with only 1 matching series: 
here graphite and MT behave the same as before. graphite is not incorrect anymore (seems coincidental in this case) though it can be argued that its output is now a bit more useful than MT's is.
![case2mt](https://user-images.githubusercontent.com/20774/27481556-65f22538-581d-11e7-806a-8781573df354.png)
![case2-graphite](https://user-images.githubusercontent.com/20774/27481557-65f7943c-581d-11e7-83db-03a05ebad4c7.png)

**Comment by Dieterbe** [comment]
so I think MT should keep using `*` when multiple series went into a sum that feeds into an aliasByNode/aliasSub function, rather then being misleading like graphite. though if only 1 series went into it, it can be clearer like graphite. (if multiple distinct series go into aliasByNode/aliasSub directly, then can each be separately accurately aliased of course, like before)
thoughts @DanCech @woodsaj

**Comment by Dieterbe** [comment]
actually, since `sum(metrictank.stats.*ops.*dr59.input.*.metric_invalid.counter32)` (despite using wildcards, only results in 1 series) results in a target output of `sumSeries(metrictank.stats.*ops.*dr59.input.*.metric_invalid.counter32)` for both graphite and MT, I think it's more than fair that we stay consistent with that and also use "*" in the aliasByNode/aliasSub output if a wildcard pattern was used to feed into a sumseries/avgseries.

so I think we can just close this and be happy with the current state of things.

**Comment by woodsaj** [comment]
regardless of what is the more correct behaviour, a dashboard using Graphite should continue working when data is moved to MT.

**Comment by Dieterbe** [comment]
> a dashboard using Graphite should continue working when data is moved to MT.

what do you mean exactly with "keep working" ? with my proposed outcome, the only edge case I can think of is a display rule might match differently, but then again it would also match differently with graphite when a series would be phased out that is matched on.  do you have anything specific against my proposition?

**Comment by woodsaj** [comment]
It is still important for MT to behave the same as graphite. If we conclude that graphite is doing something wrong and we want to correct it in MT, then we need to open an issue in graphite to have it fixed (if possible).

So open an issue in graphite, then this is good to close.

**Comment by Dieterbe** [comment]
actually it seems the latest graphite-web (i tested 1.0.1) now works like MT does, i tested both aliasByNode and aliasSub : 
```
~ ❯❯❯ curl -s 'http://localhost:8080/render/?target=carbon.agents.*.a*&from=-1minutes&format=json' | jsonpp | grep target
        "target": "carbon.agents.098a020e9c77-a.activeConnections",
        "target": "carbon.agents.098a020e9c77-a.avgUpdateTime",
~ ❯❯❯ curl -s 'http://localhost:8080/render/?target=sumSeries(carbon.agents.*.a*)&from=-1minutes&format=json' | jsonpp | grep target                                                         ⏎
        "target": "sumSeries(carbon.agents.*.a*)",
~ ❯❯❯ curl -s 'http://localhost:8080/render/?target=aliasByNode(sumSeries(carbon.agents.*.a*),3)&from=-1minutes&format=json' | jsonpp | grep target                                          ⏎
        "target": "a*",
~ ❯❯❯ curl -s "http://localhost:8080/render/?target=aliasSub(sumSeries(carbon.agents.*.a*),'carbon','foo')&from=-1minutes&format=json"
[{"target": "sumSeries(foo.agents.*.a*)", "datapoints": [[null, 1498650960]]}]% 
```
