### ISSUE TITLE
query returns 'unexpected character' when series use valid characters

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#649]
The set of characters that graphite supports in series names is

`0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&*+-/:;<>?@[]^_`|~`

as defined 
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/grammar.py#L79
with "printables" coming from https://pythonhosted.org/pyparsing/pyparsing-module.html#printables

MT using a much smaller set of chars.
https://github.com/raintank/metrictank/blob/master/expr/parse.go#L223-L231

**Comment by Dieterbe** [comment]
curious, which characters were triggering this limitation?

**Comment by woodsaj** [comment]
we had a metric using "%util" in the name.  That used to work with regular graphite, and stopped working when MT started parsing the series names.
