### ISSUE TITLE
chunks that are not persisted yet can be cleared

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#65]
this code section does not account for the chunk not being persisted yet, when it clears.
the less chunks we keep in memory, the more likely this becomes.
specifically i think for some rollup data we only want to keep 1 chunk in memory.
```
		if len(a.Chunks) < int(a.NumChunks) {
			log.Debug("adding new chunk to cirular Buffer. now %d chunks", a.CurrentChunkPos+1)
			a.Chunks = append(a.Chunks, NewChunk(t0))
		} else {
			chunkClear.Inc(1)
			log.Debug("numChunks: %d  currentPos: %d", len(a.Chunks), a.CurrentChunkPos)
			log.Debug("clearing chunk from circular buffer. %v", a.Chunks[a.CurrentChunkPos])
			a.Chunks[a.CurrentChunkPos] = NewChunk(t0)
		}
```

**Comment by woodsaj** [comment]
This is quite relevant to another problem i have been thinking about.
When we add multi-node support, we need a way to persist older chunks that have not already been persisted before persisting newer chunks.

I think the answer to both these problems is to:

* when persisting a chunk, first check that the previous chunk has been persisted. This logic will then cascade through all chunks ensuring that all chunks have been persisted.

**Comment by Dieterbe** [comment]
I believe this no longer is a problem: we now call persist() before clearing a chunk, and even when we clear a chunk (which doesn't really clean anything up) and reuse the slot for a new chunk, the CWR keeps a reference to the old chunk.
