### ISSUE TITLE
Interface for querying dumping all meta-data

### ISSUE THREAD

**Issue by shalstea** [raintank/metrictank#661]
It would be useful to be able to query/dump all meta-data about the metrics in metricTank.  We have the notion of a metric namespace (the first string prior to the . in a metric name).  Many teams that are publishing metrics would like to see all the timeseries / meta-data associated with their namespaces / metric names.

**Comment by Dieterbe** [comment]
2 suggestions for you : 
1) https://github.com/raintank/metrictank/blob/master/docs/tools.md#mt-index-cat

pro's:
* you can get all/any metadata
* works well with large volumes.
cons:
* only works with cassandra index.

2) the /metrics/find and /metrics/index.json endpoints documented at https://github.com/raintank/metrictank/blob/master/docs/http-api.md#find-all-metrics-visible-to-the-given-org and 
https://github.com/raintank/metrictank/blob/master/docs/http-api.md#walk-the-metrics-tree-and-return-every-metric-found-that-is-visible-to-the-org-as-a-sorted-json-array 
the former lets you query based on patterns, the latter just returns all.
pro's : 
* works with any index type (i.e. also with in-memory index)
cons:
* doesn't return all metadata
* can take a long lock on the index and block ingest (we plan to address this soon)
