### ISSUE TITLE
Write buffer that allows insertion of out-of-order data

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#663]
One of the common problems that we have with Metrictank is the fact that it doesn't allow the insertion of out of order data. In order to fix that I would like to introduce a write buffer which delays the compression of data by a specified amount of time, which would give us a window during which data may be out of order. It is important that this write buffer is also readable of course.

**Comment by replay** [comment]
I have already started implementing this by using a doubly linked list where each element is a datapoint. The implementation takes a minimum size setting (in datapoints) to keep before flushing them out into the compression mechanism. It is readable just like the `AggMetric` instances, but allows insertion at any timestamp within it's time window.
Obviously this data is not going to be compressed and will consume much more memory than the compressed chunks, so the reorder window needs to be kept small.

**Comment by Dieterbe** [comment]
this makes sense, though i wonder if perhaps using a map instead of a LL would perform better and/or be simpler.

> It is readable just like the AggMetric

would it make sense to implement the reorder window as a property of the AggMetric?

**Comment by replay** [comment]
Actually I've started out with a map because i thought the same ;) the problem with a map is that it will be keyed by ts (i guess), but when i consume the data and flush it into the compressed chunks i need to consume it in order. So I'd either need to build/use an ordered map or keep a separate ordered list of all timestamps in the map. Then it becomes nicer to just use one structure that i can consume in order. Furthermore the linked list implementation i'm using now has the advantage that i can consume it by splitting the list exactly at the end of the reorderWindow with only two pointer updates, and then i consume the "older" part of the split while the "newer" part of the split keeps being used. 
In my current implementation i've implemented the WriteBuffer as a separate struct which is supposed to then be embedded in to the AggMetric struct, so yes.

**Comment by Dieterbe** [comment]
ok cool. looking fwd to see your work . happy to have you back working on MT :p
