### ISSUE TITLE
indicate / error when cannot fully satisfy query

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#670]
e.g. when there is a shard which has no up-to-date replicas (rare, but can happen when multiple nodes crash), it is impossible to accurately respond to requests. currently we just serve partial data, which can lead to misleading charts and bogus alerts.
(note to self: confirm that with one up to date replicate and one refilling, the priority system works)

**Comment by woodsaj** [comment]
I think this should be pretty straight forward to address.

We already generate a list of available shards in cluster.MembersForQuery,
we just need to add a configParam for MinimumShards and make sure that len(membersMap) is greater then the MinimumShards at https://github.com/raintank/metrictank/blob/master/cluster/cluster.go#L145

If users want to have their MT cluster return partial data, they can just set minimumShards to less then the total number of shards.  eg, if there are 8 shards, setting MinimumShards=4 would have the cluster return responses as long as 50% of the shards are online.
