### ISSUE TITLE
allow from/until "now minus foo"

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#673]
`curl -v 'http://localhost:6060/render?format=json&from=-10min&maxDataPoints=500&target=foo&until=now-1min'`
results in:
```
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain
< Vary: Origin
< Date: Fri, 30 Jun 2017 14:23:33 GMT
< Content-Length: 32
< 
* Connection #0 to host localhost left intact
parse error. unknown time format
```

MT supports `-5d` and `1-min` etc but not `now-5d`.
note : 
* grafana's timepicker will often have values such as `now-6h` but will trigger requests with value `-6h`
* graphite-web does not seem to document support for the `now-foo` variant, though it does support it
* graphite-api : ditto

so MT should also support it

**Comment by replay** [comment]
Shouldn't this rather be in the `dur` project? https://github.com/raintank/dur/

**Comment by Dieterbe** [comment]
yep i pushed it to https://github.com/raintank/dur/pull/1 i couldn't add you as a reviewer there, but please do check it out when you have time :)
