### ISSUE TITLE
Queries should fail when shards unavailable

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#697]
Currently when all replicas of a shard are offline MT will just respond with the data from the available shards.

These partial responses can cause major issues for certain queries.  For example
```
asPercent(metric.*.used, metric.*.total)
```
The shards used by the `*.used` metrics will be different to the `*.total` metrics and so the percentage returned when a shard is offline could be wildly inaccurate.

Returning partial results is sometimes desirable and sometimes not.  So i think it is best if we have a configuration option for a default behaviour, but allow a per request param to override the behaviour.

**Comment by Dieterbe** [comment]
dup of #670
