### ISSUE TITLE
insert queries don't timeout

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#702]
saw a bunch of these in a stack trace: 54 hours stuck trying to insert a chunk
```
1: select [3246 minutes] [Created by mdata.NewCassandraStore @ store_cassandra.go:250]
    gocql    conn.go:637            (*Conn).exec(#698, 0, 0, 0xf636e0, #1703, 0, 0, 0, 0, 0)
    gocql    conn.go:830            (*Conn).executeQuery(#698, #1817, #445)
    gocql    session.go:750         (*Query).execute(#1817, #698, 0xfa6160)
    gocql    query_executor.go:42   (*queryExecutor).executeQuery(#99, 0xf708e0, #1817, #1170, 0x3, #1791)
    gocql    session.go:376         (*Session).executeQuery(#65, #1817, #1790)
    gocql    session.go:921         (*Query).Iter(#1817, #1817)
    gocql    session.go:904         (*Query).Exec(#1817, #548, 0x49)
    mdata    store_cassandra.go:347 (*CassandraStore).insertChunk(#160, #1285, 0x2d, #2116, #1702, 0x22, 0x40, 0, 0)
    mdata    store_cassandra.go:286 (*CassandraStore).processWriteQueue(#160, #209, #278)
```

**Comment by woodsaj** [comment]
If we timeout the write attempt, then what?  we can't just drop the data.
So i think the current behaviour is the right approach.  If we cant write to cassandra then we should stop ingesting from kafka until we can.  This allows metrics to buffer in kafka until the issue is resolved.

**Comment by Dieterbe** [comment]
hm yeah that's a good point.
I was thinking perhaps once the query has been blocked sufficiently long it becomes impsosible for it to make progress, even when the cassandra connection recovers, and if it had timed out and then retried somewhere during the 3246 minutes interval, it would have worked.
of course this is all just speculation, and to your point I think we can better just close this and use this as the desired behavior.
