### ISSUE TITLE
Whisper importer should be able to convert between retention schemas

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#710]
It would be great if the whisper importer (reader) could take an MT schema file as parameter and then generate chunks that match this schema.

For archive/aggregation that is getting generated it should look for the most suitable archive in the whisper file to use as input. 
- In the optimal case there is a whisper archive with the same resolution and TTL. 
- If there is only an archive with higher resolution and at least the same TTL, it can use the defined `consolidateBy` function to decrease the resolution.
- If there is only an archive with lower resolution that satisfies the TTL, it will have to repeat each input point factor-times.
- If even the last whisper archive (with the highest TTL) does not at least match the required TTL, then that last one is used

The above logic describes that when selecting the appropriate input archive the TTL that's being looked for is prioritized over keeping a high resolution

The goal is that when a user wants to import their whisper files, we simply provide the according `storage-schemas.conf` to them. Then they point their whisper-importer-reader at that file, from then on the whole schema conversion should just work as a part of the import.

**Comment by tehlers320** [comment]
If anybody is waiting on this and needs a work around. I just copied all my whisper files to an empty server and ran whisper-resize.py to match the new schema and then conducted the import. This may not be ideal, but it works.

**Comment by replay** [comment]
@tehlers320 you might be interested in testing that: https://github.com/raintank/metrictank/pull/712
