### ISSUE TITLE
Add to chunk cache asynchronously

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#735]
Currently the chunk cache's `.Add()` method needs to acquire cache lock in order to add chunks. This has the potential to slow down rendering, because the cache is propagated while rendering calls are served. It would be better if there was a cache internal channel through which chunks get added, so the `.Add()` method wouldn't need to lock, it would only need to push the chunks into that channel and the order would still be preserved.

**Comment by Dieterbe** [comment]
see #736 -- not clear that it's a problem at this point.
